sudo: required

language: c++

jobs:
  include:
  - name: "ubuntu"
    dist: focal
    compiler: gcc
    addons:
      apt:
        packages:
        - cmake
        - ninja-build
        - python3
        - gettext
        - libcurl4-openssl-dev
        - libicu-dev
        - qt5-default
        - libsqlite3-dev
  - name: "os_x"
    os: osx
    osx_image: xcode11.3
    addons:
      homebrew:
        packages:
          - cmake
          - ninja
          - python3
          - gettext
          - curl
          - icu4c
          - qt
          - sqlite

script:
  - DESTDIR=install cmake . -B build -G Ninja
  - cmake --build build
  - cmake --build build --target install
