env:
  global:
    - secure: "DJpN8kSerDdmx4wEyciWiTxwxFddPvEuy4TIKj3WSFyoujkeQ+uaanSjy4OeXS/GePM3t1bWz4JkF/MS1IjIhbMLnXiS/JxCerP0tjMknlmtcfj56kTePszkOngYe0aoQWp8h6m1txNRZb5ivEg/b6P45pg/6AJdQGQ+l8NWiLbWAyKcn/TV7TOnDJ7mAVCvTeInazvaYcGTF3Omsv+1wZ8PZn0eUNtywwfdaLL+RqK4cctPD0yKp8q+tHekcVIS4JqExX7pWxwghVA0B4UQX8xStRBvhIXn6atY4DHrCy6drcE0mjCFtL5i3Cuo+jJVl4yUTSz8T6fO6Eu7C0NITvNFX0h2t6TaElWLgRfGwkfG+gr4DbsoUOnpI7XsuEsRsbuXOzl52x2R0HX+Zb2Y4p6nY2gwTEMylMCnxAPkuZ9XzP2f6sA4ZZSWGQAnDUOcnoRijyl/oRba8RM4Z7iy+0U8yNebI/htfxJ4aVuvFSZDFQ+qJNqWQypW+XgW5emskFCPE07iMPpGDA0Ox/QA+uGrWtWwE/s06S9AuoWDrJlToIN4f7wyjfkIdqPoPUKsUHrVEWWwxDm9Sl4iFchfw9xq3Jrec8ZQulLVDLaMY2weMPk551UghoV2b/X2VLA0PccS7oSTM9cDMamdQr4Pqs+e9vxREF1g2X7md16SDss="

language: c++

jobs:
  include:
  - name: "ubuntu-gcc"
    dist: focal
    compiler: gcc
    addons:
      apt:
        packages:
        - cmake
        - ninja-build
        - python3
        - gettext
        - qt5-default
        - libsqlite3-dev
        - libsdl2-mixer-dev
  - name: "ubuntu-clang"
    dist: focal
    compiler: clang
    addons:
      apt:
        packages:
        - cmake
        - ninja-build
        - python3
        - gettext
        - qt5-default
        - libsqlite3-dev
        - libsdl2-mixer-dev
  - name: "os_x"
    os: osx
    osx_image: xcode11.3
    env:
      - Intl_ROOT=/usr/local/opt/gettext
      - Qt5_DIR=/usr/local/opt/qt5/lib/cmake
      - Readline_ROOT=/usr/local/opt/readline
    addons:
      homebrew:
        packages:
          - cmake
          - ninja
          - python3
          - gettext
          - qt
          - readline
          - sqlite
          - sdl2
          - sdl2_mixer
    before_script:
      - brew link gettext --force

script:
  - cmake . -B build -G Ninja -DCMAKE_INSTALL_PREFIX=$PWD/build/install
  - cmake --build build
  - cmake --build build --target install

addons:
  coverity_scan:

    project:
      name: longturn/freeciv21
      version: 0.1337
      description: Freeciv21

    #notification_email: scan_notifications@example.com

    build_command_prepend: cmake . -B covbuild -G Ninja

    build_command: cmake --build covbuild

    # Pattern to match selecting branches that will run analysis. We recommend leaving this set to 'coverity_scan'.
    branch_pattern: coverity_scan
