language: c++

jobs:
  include:
  - name: "ubuntu"
    dist: focal
    compiler: gcc
    addons:
      apt:
        packages:
        - cmake
        - ninja-build
        - python3
        - gettext
        - libcurl4-openssl-dev
        - libicu-dev
        - qt5-default
        - libsqlite3-dev
  - name: "os_x"
    os: osx
    osx_image: xcode11.3
    env:
      - ICU_ROOT=/usr/local/opt/icu4c
      - Intl_ROOT=/usr/local/opt/gettext
      - Qt5_DIR=/usr/local/opt/qt5/lib/cmake
      - Readline_ROOT=/usr/local/opt/readline
    addons:
      homebrew:
        packages:
          - cmake
          - ninja
          - python3
          - gettext
          - curl
          - icu4c
          - qt
          - readline
          - sqlite

script:
  - cmake . -B build -G Ninja -DCMAKE_INSTALL_PREFIX=$PWD/build/install
  - cmake --build build
  - cmake --build build --target install
